apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-app
  template:
    metadata:
      labels:
        app: sentiment-app
    spec:
      containers:
        - name: sentiment-app
          image: mlopsacrvr98.azurecr.io/sentiment-app:v1
          ports:
            - containerPort: 5000